if(EXISTS "C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Libraries/Properties/hello_test[1]_tests.cmake")
  include("C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Libraries/Properties/hello_test[1]_tests.cmake")
else()
  add_test(hello_test_NOT_BUILT hello_test_NOT_BUILT)
endif()
