add_test([=[MapTest.InsertAndGet]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.InsertAndGet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.InsertAndGet]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.InsertDuplicate]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.InsertDuplicate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.InsertDuplicate]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Remove]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Remove]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Remove]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Size]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Size]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Size]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.IsEmpty]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.IsEmpty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.IsEmpty]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Clear]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Clear]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Clear]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Contains]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Contains]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Contains]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.OperatorBrackets]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.OperatorBrackets]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.OperatorBrackets]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.At]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.At]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.At]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.ContainsValue]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.ContainsValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.ContainsValue]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Emplace]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Emplace]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Emplace]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Keys]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Keys]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Keys]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Values]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Values]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Values]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MapTest.Iterator]=]  C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map/Debug/hello_test.exe [==[--gtest_filter=MapTest.Iterator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MapTest.Iterator]=]  PROPERTIES WORKING_DIRECTORY C:/Users/brayd/OneDrive/Documents/GitHub/CPP-Full-Library/Map SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  hello_test_TESTS MapTest.InsertAndGet MapTest.InsertDuplicate MapTest.Remove MapTest.Size MapTest.IsEmpty MapTest.Clear MapTest.Contains MapTest.OperatorBrackets MapTest.At MapTest.ContainsValue MapTest.Emplace MapTest.Keys MapTest.Values MapTest.Iterator)
